-- 코드를 입력하세요
SELECT 
    CAR_ID, 
    CASE 
        WHEN EXISTS (
            SELECT * 
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY IC
            WHERE IC.CAR_ID = C.CAR_ID AND START_DATE <= TO_DATE('2022-10-16', 'YYYY-MM-DD') AND TO_DATE('2022-10-16', 'YYYY-MM-DD') <= END_DATE
        ) THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;